### ISSUE TITLE
PHP 8.5 not supported, magento 2.4.9 got composer require error

### ISSUE THREAD

**Issue by f123248** [amzn/amazon-payments-magento-2-plugin#1299]
composer require amzn/amazon-pay-magento-2-module

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires amzn/amazon-pay-magento-2-module * -> satisfiable by amzn/amazon-pay-magento-2-module[dev-master, dev-spc, dev-V2checkout-1.2.x, 1.0.1, ..., 1.x-dev, 2.0.15, ..., 2.x-dev, 3.0.0, ..., 3.9.0, 4.0.0, ..., 4.2.0, 5.0.0, ..., 5.18.4, 9999999-dev].
    - amzn/amazon-pay-magento-2-module[1.0.1, ..., 1.1.5] require php ~5.6.0|7.0.2|~7.0.6 -> your php version (8.5.7) does not satisfy that requirement.
    - amzn/amazon-pay-magento-2-module[1.2.0, ..., 1.x-dev] require magento/framework ^100.1.0|^101.0.0 -> found magento/framework[100.1.0-rc1, ..., 100.2.0-rc20, 101.0.0-rc21, ..., 101.0.11] but the package is fixed to 103.0.9 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - amzn/amazon-pay-magento-2-module[2.0.15, ..., 2.x-dev] require php ~7.0.13|~7.1.0 -> your php version (8.5.7) does not satisfy that requirement.
    - amzn/amazon-pay-magento-2-module[2.1.3, ..., 2.3.1, 3.0.0, ..., 3.2.11] require php ~7.1.3||~7.2.0 -> your php version (8.5.7) does not satisfy that requirement.
    - amzn/amazon-pay-magento-2-module[dev-V2checkout-1.2.x, 3.2.12, ..., 3.8.0] require php ~7.1.3||~7.2.0||~7.3.0 -> your php version (8.5.7) does not satisfy that requirement.
    - amzn/amazon-pay-magento-2-module[3.0.x-dev, ..., 3.9.0] require php ~7.1.3||~7.2.0||~7.3.0||~7.4.0 -> your php version (8.5.7) does not satisfy that requirement.
    - amzn/amazon-pay-magento-2-module[4.0.0, ..., 4.2.0] require php ~7.3.0||~7.4.0 -> your php version (8.5.7) does not satisfy that requirement.
    - amzn/amazon-pay-magento-2-module[5.0.0, ..., 5.10.0] require php ~7.0.13||~7.1.0||~7.2.0||~7.3.0||~7.4.0 -> your php version (8.5.7) does not satisfy that requirement.
    - amzn/amazon-pay-magento-2-module[5.11.0, ..., 5.14.1] require php ~7.0.13||~7.1.0||~7.2.0||~7.3.0||~7.4.0||~8.0.0||~8.1.0 -> your php version (8.5.7) does not satisfy that requirement.
    - amzn/amazon-pay-magento-2-module[dev-spc, 5.14.2, ..., 5.17.0] require php ~7.0.13||~7.1.0||~7.2.0||~7.3.0||~7.4.0||~8.0.0||~8.1.0||~8.2.0 -> your php version (8.5.7) does not satisfy that requirement.
    - amzn/amazon-pay-magento-2-module[5.17.1, ..., 5.18.2] require php ~7.0.13||~7.1.0||~7.2.0||~7.3.0||~7.4.0||~8.0.0||~8.1.0||~8.2.0||~8.3.0 -> your php version (8.5.7) does not satisfy that requirement.
    - amzn/amazon-pay-magento-2-module[dev-master, 5.18.3, ..., 5.18.4] require php ~7.1.0||~7.2.0||~7.3.0||~7.4.0||~8.0.0||~8.1.0||~8.2.0||~8.3.0||~8.4.0 -> your php version (8.5.7) does not satisfy that requirement.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require amzn/amazon-pay-magento-2-module:*" to figure out if any version is installable, or "composer require amzn/amazon-pay-magento-2-module:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by dimadidr** [comment]
Hi @f123248 ,

Thank you for reporting this issue. We are currently working on the next release for Magento 2.4.9 and PHP 8.5.

Thank you,
Dima

**Comment by sandyuke** [comment]
> Hi [@f123248](https://github.com/f123248) ,
> 
> Thank you for reporting this issue. We are currently working on the next release for Magento 2.4.9 and PHP 8.5.
> 
> Thank you, Dima

Hi Dima,

Is there any new Amazon Payme Magento extension version available now to support 2.4.9 and PHP 8.5?

**Comment by m-malik24** [comment]
Hi, is there any update available for magento 2.4.9?
Fatal error: Declaration of Amazon\Pay\Command\Async\ProcessCommand::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output) must be compatible with Symfony\Component\Console\Command\Command::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output): int in /var/www/html/vendor/amzn/amazon-pay-magento-2-module/Command/Async/ProcessCommand.php on line 66

**Comment by dimadidr** [comment]
Hi @sandyuke , @m-malik24 

There is a PR  for Release/5.18.5: https://github.com/amzn/amazon-payments-magento-2-plugin/pull/1301.

It includes:
- Added compatibility with PHP 8.5
- Fixed JavaScript error "$elem.uniqueId is not a function" on checkout
- Fixed compatibility with newer Symfony versions

Once it is merged, the new release will be available.

Thank you,
Dima

**Comment by m-malik24** [comment]
@dimadidr  Is there any chance someone is actively reviewing the open PRs and planning a new release for the compatibility fixes? Magento 2.4.9 was released several months ago, but Amazon Pay still hasn't published an updated version with the necessary compatibility changes.

**Comment by f123248** [comment]
Hi @dimadidr ,

I found the PR still have some issue.
It happened when the amazon pay is installed but not enable for the using store view.
It broke the mini cart & proceed to checkout button.
{"message":"Deprecated Functionality: Using null as the key parameter for array_key_exists() is deprecated, use an empty string instead in \/var\/\html/vendor\/amzn\/amazon-pay-magento-2-module\/Model\/AmazonConfig.php on line 301"}
